const countries = [
  {
    name: "Afghanistan",
    capital: "Kabul",
    languages: ["Pashto", "Uzbek", "Turkmen"],
    population: 27657145,
    currency: "Afghan afghani",
    code: "AF",
  },
  {
    name: "Åland Islands",
    capital: "Mariehamn",
    languages: ["Swedish"],
    population: 28875,
    currency: "Euro",
    code: "AX",
  },
  {
    name: "Albania",
    capital: "Tirana",
    languages: ["Albanian"],
    population: 2886026,
    currency: "Albanian lek",
    code: "AL",
  },
  {
    name: "Algeria",
    capital: "Algiers",
    languages: ["Arabic"],
    population: 40400000,
    currency: "Algerian dinar",
    code: "DZ",
  },
  {
    name: "American Samoa",
    capital: "Pago Pago",
    languages: ["English", "Samoan"],
    population: 57100,
    currency: "United State Dollar",
    code: "AS",
  },
  {
    name: "Angola",
    capital: "Luanda",
    languages: ["Portuguese"],
    population: 25868000,
    currency: "Angolan kwanza",
    code: "AO",
  },
  {
    name: "Anguilla",
    capital: "The Valley",
    languages: ["English"],
    population: 13452,
    currency: "East Caribbean dollar",
    code: "AI",
  },
  {
    name: "Antarctica",
    capital: "",
    languages: ["English", "Russian"],
    population: 1000,
    currency: "Australian dollar",
    code: "AQ",
  },
  {
    name: "Antigua and Barbuda",
    capital: "Saint John's",
    languages: ["English"],
    population: 86295,
    currency: "East Caribbean dollar",
    code: "AG",
  },
  {
    name: "Argentina",
    capital: "Buenos Aires",
    languages: ["Spanish", "Guaraní"],
    population: 43590400,
    currency: "Argentine peso",
    code: "AR",
  },
  {
    name: "Armenia",
    capital: "Yerevan",
    languages: ["Armenian", "Russian"],
    population: 2994400,
    currency: "Armenian dram",
    code: "AM",
  },
  {
    name: "Aruba",
    capital: "Oranjestad",
    languages: ["Dutch", "(Eastern) Punjabi"],
    population: 107394,
    currency: "Aruban florin",
    code: "AW",
  },
  {
    name: "Australia",
    capital: "Canberra",
    languages: ["English"],
    population: 24117360,
    currency: "Australian dollar",
    code: "AU",
  },
  {
    name: "Austria",
    capital: "Vienna",
    languages: ["German"],
    population: 8725931,
    currency: "Euro",
    code: "AT",
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    languages: ["Azerbaijani"],
    population: 9730500,
    currency: "Azerbaijani manat",
    code: "AZ",
  },
  {
    name: "Bahamas",
    capital: "Nassau",
    languages: ["English"],
    population: 378040,
    currency: "Bahamian dollar",
    code: "BS",
  },
  {
    name: "Bahrain",
    capital: "Manama",
    languages: ["Arabic"],
    population: 1404900,
    currency: "Bahraini dinar",
    code: "BH",
  },
  {
    name: "Bangladesh",
    capital: "Dhaka",
    languages: ["Bengali"],
    population: 161006790,
    currency: "Bangladeshi taka",
    code: "BD",
  },
  {
    name: "Barbados",
    capital: "Bridgetown",
    languages: ["English"],
    population: 285000,
    currency: "Barbadian dollar",
    code: "BB",
  },
  {
    name: "Belarus",
    capital: "Minsk",
    languages: ["Belarusian", "Russian"],
    population: 9498700,
    currency: "New Belarusian ruble",
    code: "BY",
  },
  {
    name: "Belgium",
    capital: "Brussels",
    languages: ["Dutch", "French", "German"],
    population: 11319511,
    currency: "Euro",
    code: "BE",
  },
  {
    name: "Belize",
    capital: "Belmopan",
    languages: ["English", "Spanish"],
    population: 370300,
    currency: "Belize dollar",
    code: "BZ",
  },
  {
    name: "Benin",
    capital: "Porto-Novo",
    languages: ["French"],
    population: 10653654,
    currency: "West African CFA franc",
    code: "BJ",
  },
  {
    name: "Bermuda",
    capital: "Hamilton",
    languages: ["English"],
    population: 61954,
    currency: "Bermudian dollar",
    code: "BM",
  },
  {
    name: "Bhutan",
    capital: "Thimphu",
    languages: ["Dzongkha"],
    population: 775620,
    currency: "Bhutanese ngultrum",
    code: "BT",
  },
  {
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    languages: ["Bosnian", "Croatian", "Serbian"],
    population: 3531159,
    currency: "Bosnia and Herzegovina convertible mark",
    code: "BA",
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    languages: ["English", "Tswana"],
    population: 2141206,
    currency: "Botswana pula",
    code: "BW",
  },
  {
    name: "Bouvet Island",
    capital: "",
    languages: ["Norwegian", "Norwegian Bokmål", "Norwegian Nynorsk"],
    population: 0,
    currency: "Norwegian krone",
    code: "BV",
  },
  {
    name: "Brazil",
    capital: "Brasília",
    languages: ["Portuguese"],
    population: 206135893,
    currency: "Brazilian real",
    code: "BR",
  },
  {
    name: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    languages: ["English"],
    population: 3000,
    currency: "United States dollar",
    code: "IO",
  },
  {
    name: "Brunei Darussalam",
    capital: "Bandar Seri Begawan",
    languages: ["Malay"],
    population: 411900,
    currency: "Brunei dollar",
    code: "BN",
  },
  {
    name: "Bulgaria",
    capital: "Sofia",
    languages: ["Bulgarian"],
    population: 7153784,
    currency: "Bulgarian lev",
    code: "BG",
  },
  {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    languages: ["French", "Fula"],
    population: 19034397,
    currency: "West African CFA franc",
    code: "BF",
  },
  {
    name: "Burundi",
    capital: "Bujumbura",
    languages: ["French", "Kirundi"],
    population: 10114505,
    currency: "Burundian franc",
    code: "BI",
  },
  {
    name: "Cambodia",
    capital: "Phnom Penh",
    languages: ["Khmer"],
    population: 15626444,
    currency: "Cambodian riel",
    code: "KH",
  },
  {
    name: "Cameroon",
    capital: "Yaoundé",
    languages: ["English", "French"],
    population: 22709892,
    currency: "Central African CFA franc",
    code: "CM",
  },
  {
    name: "Canada",
    capital: "Ottawa",
    languages: ["English", "French"],
    population: 36155487,
    currency: "Canadian dollar",
    code: "CA",
  },
  {
    name: "Cayman Islands",
    capital: "George Town",
    languages: ["English"],
    population: 58238,
    currency: "Cayman Islands dollar",
    code: "KY",
  },
  {
    name: "Central African Republic",
    capital: "Bangui",
    languages: ["French", "Sango"],
    population: 4998000,
    currency: "Central African CFA franc",
    code: "CF",
  },
  {
    name: "Chad",
    capital: "N'Djamena",
    languages: ["French", "Arabic"],
    population: 14497000,
    currency: "Central African CFA franc",
    code: "TD",
  },
  {
    name: "Chile",
    capital: "Santiago",
    languages: ["Spanish"],
    population: 18191900,
    currency: "Chilean peso",
    code: "CL",
  },
  {
    name: "China",
    capital: "Beijing",
    languages: ["Chinese"],
    population: 1377422166,
    currency: "Chinese yuan",
    code: "CN",
  },
  {
    name: "Christmas Island",
    capital: "Flying Fish Cove",
    languages: ["English"],
    population: 2072,
    currency: "Australian dollar",
    code: "CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    capital: "West Island",
    languages: ["English"],
    population: 550,
    currency: "Australian dollar",
    code: "CC",
  },
  {
    name: "Colombia",
    capital: "Bogotá",
    languages: ["Spanish"],
    population: 48759958,
    currency: "Colombian peso",
    code: "CO",
  },
  {
    name: "Comoros",
    capital: "Moroni",
    languages: ["Arabic", "French"],
    population: 806153,
    currency: "Comorian franc",
    code: "KM",
  },
  {
    name: "Congo",
    capital: "Brazzaville",
    languages: ["French", "Lingala"],
    population: 4741000,
    currency: "Central African CFA franc",
    code: "CG",
  },
  {
    name: "Cook Islands",
    capital: "Avarua",
    languages: ["English"],
    population: 18100,
    currency: "New Zealand dollar",
    code: "CK",
  },
  {
    name: "Costa Rica",
    capital: "San José",
    languages: ["Spanish"],
    population: 4890379,
    currency: "Costa Rican colón",
    code: "CR",
  },
  {
    name: "Croatia",
    capital: "Zagreb",
    languages: ["Croatian"],
    population: 4190669,
    currency: "Croatian kuna",
    code: "HR",
  },
  {
    name: "Cuba",
    capital: "Havana",
    languages: ["Spanish"],
    population: 11239004,
    currency: "Cuban convertible peso",
    code: "CU",
  },
  {
    name: "Cyprus",
    capital: "Nicosia",
    languages: ["Greek (modern)", "Turkish", "Armenian"],
    population: 847000,
    currency: "Euro",
    code: "CY",
  },
  {
    name: "Czech Republic",
    capital: "Prague",
    languages: ["Czech", "Slovak"],
    population: 10558524,
    currency: "Czech koruna",
    code: "CZ",
  },
  {
    name: "Denmark",
    capital: "Copenhagen",
    languages: ["Danish"],
    population: 5717014,
    currency: "Danish krone",
    code: "DK",
  },
  {
    name: "Djibouti",
    capital: "Djibouti",
    languages: ["French", "Arabic"],
    population: 900000,
    currency: "Djiboutian franc",
    code: "DJ",
  },
  {
    name: "Dominica",
    capital: "Roseau",
    languages: ["English"],
    population: 71293,
    currency: "East Caribbean dollar",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    languages: ["Spanish"],
    population: 10075045,
    currency: "Dominican peso",
    code: "DO",
  },
  {
    name: "Ecuador",
    capital: "Quito",
    languages: ["Spanish"],
    population: 16545799,
    currency: "United States dollar",
    code: "EC",
  },
  {
    name: "Egypt",
    capital: "Cairo",
    languages: ["Arabic"],
    population: 91290000,
    currency: "Egyptian pound",
    code: "EG",
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    languages: ["Spanish"],
    population: 6520675,
    currency: "United States dollar",
    code: "SV",
  },
  {
    name: "Equatorial Guinea",
    capital: "Malabo",
    languages: ["Spanish", "French"],
    population: 1222442,
    currency: "Central African CFA franc",
    code: "GQ",
  },
  {
    name: "Eritrea",
    capital: "Asmara",
    languages: ["Tigrinya", "Arabic", "English"],
    population: 5352000,
    currency: "Eritrean nakfa",
    code: "ER",
  },
  {
    name: "Estonia",
    capital: "Tallinn",
    languages: ["Estonian"],
    population: 1315944,
    currency: "Euro",
    code: "EE",
  },
  {
    name: "Ethiopia",
    capital: "Addis Ababa",
    languages: ["Amharic"],
    population: 92206005,
    currency: "Ethiopian birr",
    code: "ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    capital: "Stanley",
    languages: ["English"],
    population: 2563,
    currency: "Falkland Islands pound",
    code: "FK",
  },
  {
    name: "Faroe Islands",
    capital: "Tórshavn",
    languages: ["Faroese"],
    population: 49376,
    currency: "Danish krone",
    code: "FO",
  },
  {
    name: "Fiji",
    capital: "Suva",
    languages: ["English", "Fijian", "Hindi", "Urdu"],
    population: 867000,
    currency: "Fijian dollar",
    code: "FJ",
  },
  {
    name: "Finland",
    capital: "Helsinki",
    languages: ["Finnish", "Swedish"],
    population: 5491817,
    currency: "Euro",
    code: "FI",
  },
  {
    name: "France",
    capital: "Paris",
    languages: ["French"],
    population: 66710000,
    currency: "Euro",
    code: "FR",
  },
  {
    name: "French Guiana",
    capital: "Cayenne",
    languages: ["French"],
    population: 254541,
    currency: "Euro",
    code: "GF",
  },
  {
    name: "French Polynesia",
    capital: "Papeetē",
    languages: ["French"],
    population: 271800,
    currency: "CFP franc",
    code: "PF",
  },
  {
    name: "French Southern Territories",
    capital: "Port-aux-Français",
    languages: ["French"],
    population: 140,
    currency: "Euro",
    code: "TF",
  },
  {
    name: "Gabon",
    capital: "Libreville",
    languages: ["French"],
    population: 1802278,
    currency: "Central African CFA franc",
    code: "GA",
  },
  {
    name: "Gambia",
    capital: "Banjul",
    languages: ["English"],
    population: 1882450,
    currency: "Gambian dalasi",
    code: "GM",
  },
  {
    name: "Georgia",
    capital: "Tbilisi",
    languages: ["Georgian"],
    population: 3720400,
    currency: "Georgian Lari",
    code: "GE",
  },
  {
    name: "Germany",
    capital: "Berlin",
    languages: ["German"],
    population: 81770900,
    currency: "Euro",
    code: "DE",
  },
  {
    name: "Ghana",
    capital: "Accra",
    languages: ["English"],
    population: 27670174,
    currency: "Ghanaian cedi",
    code: "GH",
  },
  {
    name: "Gibraltar",
    capital: "Gibraltar",
    languages: ["English"],
    population: 33140,
    currency: "Gibraltar pound",
    code: "GI",
  },
  {
    name: "Greece",
    capital: "Athens",
    languages: ["Greek (modern)"],
    population: 10858018,
    currency: "Euro",
    code: "GR",
  },
  {
    name: "Greenland",
    capital: "Nuuk",
    languages: ["Kalaallisut"],
    population: 55847,
    currency: "Danish krone",
    code: "GL",
  },
  {
    name: "Grenada",
    capital: "St. George's",
    languages: ["English"],
    population: 103328,
    currency: "East Caribbean dollar",
    code: "GD",
  },
  {
    name: "Guadeloupe",
    capital: "Basse-Terre",
    languages: ["French"],
    population: 400132,
    currency: "Euro",
    code: "GP",
  },
  {
    name: "Guam",
    capital: "Hagåtña",
    languages: ["English", "Chamorro", "Spanish"],
    population: 184200,
    currency: "United States dollar",
    code: "GU",
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    languages: ["Spanish"],
    population: 16176133,
    currency: "Guatemalan quetzal",
    code: "GT",
  },
  {
    name: "Guernsey",
    capital: "St. Peter Port",
    languages: ["English", "French"],
    population: 62999,
    currency: "British pound",
    code: "GG",
  },
  {
    name: "Guinea",
    capital: "Conakry",
    languages: ["French", "Fula"],
    population: 12947000,
    currency: "Guinean franc",
    code: "GN",
  },
  {
    name: "Guinea-Bissau",
    capital: "Bissau",
    languages: ["Portuguese"],
    population: 1547777,
    currency: "West African CFA franc",
    code: "GW",
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    languages: ["English"],
    population: 746900,
    currency: "Guyanese dollar",
    code: "GY",
  },
  {
    name: "Haiti",
    capital: "Port-au-Prince",
    languages: ["French", "Haitian"],
    population: 11078033,
    currency: "Haitian gourde",
    code: "HT",
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    languages: ["Spanish"],
    population: 8576532,
    currency: "Honduran lempira",
    code: "HN",
  },
  {
    name: "Hong Kong",
    capital: "City of Victoria",
    languages: ["English", "Chinese"],
    population: 7324300,
    currency: "Hong Kong dollar",
    code: "HK",
  },
  {
    name: "Hungary",
    capital: "Budapest",
    languages: ["Hungarian"],
    population: 9823000,
    currency: "Hungarian forint",
    code: "HU",
  },
  {
    name: "Iceland",
    capital: "Reykjavík",
    languages: ["Icelandic"],
    population: 334300,
    currency: "Icelandic króna",
    code: "IS",
  },
  {
    name: "India",
    capital: "New Delhi",
    languages: ["Hindi", "English"],
    population: 1295210000,
    currency: "Indian rupee",
    code: "IN",
  },
  {
    name: "Indonesia",
    capital: "Jakarta",
    languages: ["Indonesian"],
    population: 258705000,
    currency: "Indonesian rupiah",
    code: "ID",
  },
  {
    name: "Iraq",
    capital: "Baghdad",
    languages: ["Arabic", "Kurdish"],
    population: 37883543,
    currency: "Iraqi dinar",
    code: "IQ",
  },
  {
    name: "Ireland",
    capital: "Dublin",
    languages: ["Irish", "English"],
    population: 6378000,
    currency: "Euro",
    code: "IE",
  },
  {
    name: "Isle of Man",
    capital: "Douglas",
    languages: ["English", "Manx"],
    population: 84497,
    currency: "British pound",
    code: "IM",
  },
  {
    name: "Israel",
    capital: "Jerusalem",
    languages: ["Hebrew (modern)", "Arabic"],
    population: 8527400,
    currency: "Israeli new shekel",
    code: "IL",
  },
  {
    name: "Italy",
    capital: "Rome",
    languages: ["Italian"],
    population: 60665551,
    currency: "Euro",
    code: "IT",
  },
  {
    name: "Jamaica",
    capital: "Kingston",
    languages: ["English"],
    population: 2723246,
    currency: "Jamaican dollar",
    code: "JM",
  },
  {
    name: "Japan",
    capital: "Tokyo",
    languages: ["Japanese"],
    population: 126960000,
    currency: "Japanese yen",
    code: "JP",
  },
  {
    name: "Jersey",
    capital: "Saint Helier",
    languages: ["English", "French"],
    population: 100800,
    currency: "British pound",
    code: "JE",
  },
  {
    name: "Jordan",
    capital: "Amman",
    languages: ["Arabic"],
    population: 9531712,
    currency: "Jordanian dinar",
    code: "JO",
  },
  {
    name: "Kazakhstan",
    capital: "Astana",
    languages: ["Kazakh", "Russian"],
    population: 17753200,
    currency: "Kazakhstani tenge",
    code: "KZ",
  },
  {
    name: "Kenya",
    capital: "Nairobi",
    languages: ["English", "Swahili"],
    population: 47251000,
    currency: "Kenyan shilling",
    code: "KE",
  },
  {
    name: "Kiribati",
    capital: "South Tarawa",
    languages: ["English"],
    population: 113400,
    currency: "Australian dollar",
    code: "KI",
  },
  {
    name: "Kuwait",
    capital: "Kuwait City",
    languages: ["Arabic"],
    population: 4183658,
    currency: "Kuwaiti dinar",
    code: "KW",
  },
  {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    languages: ["Kyrgyz", "Russian"],
    population: 6047800,
    currency: "Kyrgyzstani som",
    code: "KG",
  },
  {
    name: "Latvia",
    capital: "Riga",
    languages: ["Latvian"],
    population: 1961600,
    currency: "Euro",
    code: "LV",
  },
  {
    name: "Lebanon",
    capital: "Beirut",
    languages: ["Arabic", "French"],
    population: 5988000,
    currency: "Lebanese pound",
    code: "LB",
  },
  {
    name: "Lesotho",
    capital: "Maseru",
    languages: ["English", "Southern Sotho"],
    population: 1894194,
    currency: "Lesotho loti",
    code: "LS",
  },
  {
    name: "Liberia",
    capital: "Monrovia",
    languages: ["English"],
    population: 4615000,
    currency: "Liberian dollar",
    code: "LR",
  },
  {
    name: "Liechtenstein",
    capital: "Vaduz",
    languages: ["German"],
    population: 37623,
    currency: "Swiss franc",
    code: "LI",
  },
  {
    name: "Lithuania",
    capital: "Vilnius",
    languages: ["Lithuanian"],
    population: 2872294,
    currency: "Euro",
    code: "LT",
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg",
    languages: ["French", "German", "Luxembourgish"],
    population: 576200,
    currency: "Euro",
    code: "LU",
  },
  {
    name: "Macao",
    capital: "",
    languages: ["Chinese", "Portuguese"],
    population: 649100,
    currency: "Macanese pataca",
    code: "MO",
  },
  {
    name: "Madagascar",
    capital: "Antananarivo",
    languages: ["French", "Malagasy"],
    population: 22434363,
    currency: "Malagasy ariary",
    code: "MG",
  },
  {
    name: "Malawi",
    capital: "Lilongwe",
    languages: ["English", "Chichewa"],
    population: 16832910,
    currency: "Malawian kwacha",
    code: "MW",
  },
  {
    name: "Malaysia",
    capital: "Kuala Lumpur",
    languages: ["Malaysian"],
    population: 31405416,
    currency: "Malaysian ringgit",
    code: "MY",
  },
  {
    name: "Maldives",
    capital: "Malé",
    languages: ["Divehi"],
    population: 344023,
    currency: "Maldivian rufiyaa",
    code: "MV",
  },
  {
    name: "Mali",
    capital: "Bamako",
    languages: ["French"],
    population: 18135000,
    currency: "West African CFA franc",
    code: "ML",
  },
  {
    name: "Malta",
    capital: "Valletta",
    languages: ["Maltese", "English"],
    population: 425384,
    currency: "Euro",
    code: "MT",
  },
  {
    name: "Marshall Islands",
    capital: "Majuro",
    languages: ["English", "Marshallese"],
    population: 54880,
    currency: "United States dollar",
    code: "MH",
  },
  {
    name: "Martinique",
    capital: "Fort-de-France",
    languages: ["French"],
    population: 378243,
    currency: "Euro",
    code: "MQ",
  },
  {
    name: "Mauritania",
    capital: "Nouakchott",
    languages: ["Arabic"],
    population: 3718678,
    currency: "Mauritanian ouguiya",
    code: "MR",
  },
  {
    name: "Mauritius",
    capital: "Port Louis",
    languages: ["English"],
    population: 1262879,
    currency: "Mauritian rupee",
    code: "MU",
  },
  {
    name: "Mayotte",
    capital: "Mamoudzou",
    languages: ["French"],
    population: 226915,
    currency: "Euro",
    code: "YT",
  },
  {
    name: "Mexico",
    capital: "Mexico City",
    languages: ["Spanish"],
    population: 122273473,
    currency: "Mexican peso",
    code: "MX",
  },
  {
    name: "Monaco",
    capital: "Monaco",
    languages: ["French"],
    population: 38400,
    currency: "Euro",
    code: "MC",
  },
  {
    name: "Mongolia",
    capital: "Ulan Bator",
    languages: ["Mongolian"],
    population: 3093100,
    currency: "Mongolian tögrög",
    code: "MN",
  },
  {
    name: "Montenegro",
    capital: "Podgorica",
    languages: ["Serbian", "Bosnian", "Albanian", "Croatian"],
    population: 621810,
    currency: "Euro",
    code: "ME",
  },
  {
    name: "Montserrat",
    capital: "Plymouth",
    languages: ["English"],
    population: 4922,
    currency: "East Caribbean dollar",
    code: "MS",
  },
  {
    name: "Morocco",
    capital: "Rabat",
    languages: ["Arabic"],
    population: 33337529,
    currency: "Moroccan dirham",
    code: "MA",
  },
  {
    name: "Mozambique",
    capital: "Maputo",
    languages: ["Portuguese"],
    population: 26423700,
    currency: "Mozambican metical",
    code: "MZ",
  },
  {
    name: "Myanmar",
    capital: "Naypyidaw",
    languages: ["Burmese"],
    population: 51419420,
    currency: "Burmese kyat",
    code: "MM",
  },
  {
    name: "Namibia",
    capital: "Windhoek",
    languages: ["English", "Afrikaans"],
    population: 2324388,
    currency: "Namibian dollar",
    code: "NA",
  },
  {
    name: "Nauru",
    capital: "Yaren",
    languages: ["English", "Nauruan"],
    population: 10084,
    currency: "Australian dollar",
    code: "NR",
  },
  {
    name: "Nepal",
    capital: "Kathmandu",
    languages: ["Nepali"],
    population: 28431500,
    currency: "Nepalese rupee",
    code: "NP",
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    languages: ["Dutch"],
    population: 17019800,
    currency: "Euro",
    code: "NL",
  },
  {
    name: "New Caledonia",
    capital: "Nouméa",
    languages: ["French"],
    population: 268767,
    currency: "CFP franc",
    code: "NC",
  },
  {
    name: "New Zealand",
    capital: "Wellington",
    languages: ["English", "Māori"],
    population: 4697854,
    currency: "New Zealand dollar",
    code: "NZ",
  },
  {
    name: "Nicaragua",
    capital: "Managua",
    languages: ["Spanish"],
    population: 6262703,
    currency: "Nicaraguan córdoba",
    code: "NI",
  },
  {
    name: "Niger",
    capital: "Niamey",
    languages: ["French"],
    population: 20715000,
    currency: "West African CFA franc",
    code: "NE",
  },
  {
    name: "Nigeria",
    capital: "Abuja",
    languages: ["English"],
    population: 186988000,
    currency: "Nigerian naira",
    code: "NG",
  },
  {
    name: "Niue",
    capital: "Alofi",
    languages: ["English"],
    population: 1470,
    currency: "New Zealand dollar",
    code: "NU",
  },
  {
    name: "Norfolk Island",
    capital: "Kingston",
    languages: ["English"],
    population: 2302,
    currency: "Australian dollar",
    code: "NF",
  },
  {
    name: "Northern Mariana Islands",
    capital: "Saipan",
    languages: ["English", "Chamorro"],
    population: 56940,
    currency: "United States dollar",
    code: "MP",
  },
  {
    name: "Norway",
    capital: "Oslo",
    languages: ["Norwegian", "Norwegian Bokmål", "Norwegian Nynorsk"],
    population: 5223256,
    currency: "Norwegian krone",
    code: "NO",
  },
  {
    name: "Oman",
    capital: "Muscat",
    languages: ["Arabic"],
    population: 4420133,
    currency: "Omani rial",
    code: "OM",
  },
  {
    name: "Pakistan",
    capital: "Islamabad",
    languages: ["English", "Urdu"],
    population: 194125062,
    currency: "Pakistani rupee",
    code: "PK",
  },
  {
    name: "Palau",
    capital: "Ngerulmud",
    languages: ["English"],
    population: 17950,
    currency: "[E]",
    code: "PW",
  },
  {
    name: "Panama",
    capital: "Panama City",
    languages: ["Spanish"],
    population: 3814672,
    currency: "Panamanian balboa",
    code: "PA",
  },
  {
    name: "Papua New Guinea",
    capital: "Port Moresby",
    languages: ["English"],
    population: 8083700,
    currency: "Papua New Guinean kina",
    code: "PG",
  },
  {
    name: "Paraguay",
    capital: "Asunción",
    languages: ["Spanish", "Guaraní"],
    population: 6854536,
    currency: "Paraguayan guaraní",
    code: "PY",
  },
  {
    name: "Peru",
    capital: "Lima",
    languages: ["Spanish"],
    population: 31488700,
    currency: "Peruvian sol",
    code: "PE",
  },
  {
    name: "Philippines",
    capital: "Manila",
    languages: ["English"],
    population: 103279800,
    currency: "Philippine peso",
    code: "PH",
  },
  {
    name: "Pitcairn",
    capital: "Adamstown",
    languages: ["English"],
    population: 56,
    currency: "New Zealand dollar",
    code: "PN",
  },
  {
    name: "Poland",
    capital: "Warsaw",
    languages: ["Polish"],
    population: 38437239,
    currency: "Polish złoty",
    code: "PL",
  },
  {
    name: "Portugal",
    capital: "Lisbon",
    languages: ["Portuguese"],
    population: 10374822,
    currency: "Euro",
    code: "PT",
  },
  {
    name: "Puerto Rico",
    capital: "San Juan",
    languages: ["Spanish", "English"],
    population: 3474182,
    currency: "United States dollar",
    code: "PR",
  },
  {
    name: "Qatar",
    capital: "Doha",
    languages: ["Arabic"],
    population: 2587564,
    currency: "Qatari riyal",
    code: "QA",
  },
  {
    name: "Romania",
    capital: "Bucharest",
    languages: ["Romanian"],
    population: 19861408,
    currency: "Romanian leu",
    code: "RO",
  },
  {
    name: "Russian Federation",
    capital: "Moscow",
    languages: ["Russian"],
    population: 146599183,
    currency: "Russian ruble",
    code: "RU",
  },
  {
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    languages: ["English"],
    population: 46204,
    currency: "East Caribbean dollar",
    code: "KN",
  },
  {
    name: "Saint Lucia",
    capital: "Castries",
    languages: ["English"],
    population: 186000,
    currency: "East Caribbean dollar",
    code: "LC",
  },
  {
    name: "Saint Pierre and Miquelon",
    capital: "Saint-Pierre",
    languages: ["French"],
    population: 6069,
    currency: "Euro",
    code: "PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    languages: ["English"],
    population: 109991,
    currency: "East Caribbean dollar",
    code: "VC",
  },
  {
    name: "Samoa",
    capital: "Apia",
    languages: ["Samoan", "English"],
    population: 194899,
    currency: "Samoan tālā",
    code: "WS",
  },
  {
    name: "San Marino",
    capital: "City of San Marino",
    languages: ["Italian"],
    population: 33005,
    currency: "Euro",
    code: "SM",
  },
  {
    name: "Sao Tome and Principe",
    capital: "São Tomé",
    languages: ["Portuguese"],
    population: 187356,
    currency: "São Tomé and Príncipe dobra",
    code: "ST",
  },
  {
    name: "Saudi Arabia",
    capital: "Riyadh",
    languages: ["Arabic"],
    population: 32248200,
    currency: "Saudi riyal",
    code: "SA",
  },
  {
    name: "Senegal",
    capital: "Dakar",
    languages: ["French"],
    population: 14799859,
    currency: "West African CFA franc",
    code: "SN",
  },
  {
    name: "Serbia",
    capital: "Belgrade",
    languages: ["Serbian"],
    population: 7076372,
    currency: "Serbian dinar",
    code: "RS",
  },
  {
    name: "Seychelles",
    capital: "Victoria",
    languages: ["French", "English"],
    population: 91400,
    currency: "Seychellois rupee",
    code: "SC",
  },
  {
    name: "Sierra Leone",
    capital: "Freetown",
    languages: ["English"],
    population: 7075641,
    currency: "Sierra Leonean leone",
    code: "SL",
  },
  {
    name: "Singapore",
    capital: "Singapore",
    languages: ["English", "Malay", "Tamil", "Chinese"],
    population: 5535000,
    currency: "Brunei dollar",
    code: "SG",
  },
  {
    name: "Slovakia",
    capital: "Bratislava",
    languages: ["Slovak"],
    population: 5426252,
    currency: "Euro",
    code: "SK",
  },
  {
    name: "Slovenia",
    capital: "Ljubljana",
    languages: ["Slovene"],
    population: 2064188,
    currency: "Euro",
    code: "SI",
  },
  {
    name: "Solomon Islands",
    capital: "Honiara",
    languages: ["English"],
    population: 642000,
    currency: "Solomon Islands dollar",
    code: "SB",
  },
  {
    name: "Somalia",
    capital: "Mogadishu",
    languages: ["Somali", "Arabic"],
    population: 11079000,
    currency: "Somali shilling",
    code: "SO",
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    languages: [
      "Afrikaans",
      "English",
      "Southern Ndebele",
      "Southern Sotho",
      "Swati",
      "Tswana",
      "Tsonga",
      "Venda",
      "Xhosa",
      "Zulu",
    ],
    population: 55653654,
    currency: "South African rand",
    code: "ZA",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    capital: "King Edward Point",
    languages: ["English"],
    population: 30,
    currency: "British pound",
    code: "GS",
  },
  {
    name: "Spain",
    capital: "Madrid",
    languages: ["Spanish"],
    population: 46438422,
    currency: "Euro",
    code: "ES",
  },
  {
    name: "Sri Lanka",
    capital: "Colombo",
    languages: ["Sinhalese", "Tamil"],
    population: 20966000,
    currency: "Sri Lankan rupee",
    code: "LK",
  },
  {
    name: "Sudan",
    capital: "Khartoum",
    languages: ["Arabic", "English"],
    population: 39598700,
    currency: "Sudanese pound",
    code: "SD",
  },
  {
    name: "Suriname",
    capital: "Paramaribo",
    languages: ["Dutch"],
    population: 541638,
    currency: "Surinamese dollar",
    code: "SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    capital: "Longyearbyen",
    languages: ["Norwegian"],
    population: 2562,
    currency: "Norwegian krone",
    code: "SJ",
  },
  {
    name: "Swaziland",
    capital: "Lobamba",
    languages: ["English", "Swati"],
    population: 1132657,
    currency: "Swazi lilangeni",
    code: "SZ",
  },
  {
    name: "Sweden",
    capital: "Stockholm",
    languages: ["Swedish"],
    population: 9894888,
    currency: "Swedish krona",
    code: "SE",
  },
  {
    name: "Switzerland",
    capital: "Bern",
    languages: ["German", "French", "Italian"],
    population: 8341600,
    currency: "Swiss franc",
    code: "CH",
  },
  {
    name: "Syrian Arab Republic",
    capital: "Damascus",
    languages: ["Arabic"],
    population: 18564000,
    currency: "Syrian pound",
    code: "SY",
  },
  {
    name: "Tajikistan",
    capital: "Dushanbe",
    languages: ["Tajik", "Russian"],
    population: 8593600,
    currency: "Tajikistani somoni",
    code: "TJ",
  },
  {
    name: "Tanzania, United Republic of",
    capital: "Dodoma",
    languages: ["Swahili", "English"],
    population: 55155000,
    currency: "Tanzanian shilling",
    code: "TZ",
  },
  {
    name: "Thailand",
    capital: "Bangkok",
    languages: ["Thai"],
    population: 65327652,
    currency: "Thai baht",
    code: "TH",
  },
  {
    name: "Timor-Leste",
    capital: "Dili",
    languages: ["Portuguese"],
    population: 1167242,
    currency: "United States dollar",
    code: "TL",
  },
  {
    name: "Togo",
    capital: "Lomé",
    languages: ["French"],
    population: 7143000,
    currency: "West African CFA franc",
    code: "TG",
  },
  {
    name: "Tokelau",
    capital: "Fakaofo",
    languages: ["English"],
    population: 1411,
    currency: "New Zealand dollar",
    code: "TK",
  },
  {
    name: "Tonga",
    capital: "Nuku'alofa",
    languages: ["English", "Tonga (Tonga Islands)"],
    population: 103252,
    currency: "Tongan paʻanga",
    code: "TO",
  },
  {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    languages: ["English"],
    population: 1349667,
    currency: "Trinidad and Tobago dollar",
    code: "TT",
  },
  {
    name: "Tunisia",
    capital: "Tunis",
    languages: ["Arabic"],
    population: 11154400,
    currency: "Tunisian dinar",
    code: "TN",
  },
  {
    name: "Turkey",
    capital: "Ankara",
    languages: ["Turkish"],
    population: 78741053,
    currency: "Turkish lira",
    code: "TR",
  },
  {
    name: "Turkmenistan",
    capital: "Ashgabat",
    languages: ["Turkmen", "Russian"],
    population: 4751120,
    currency: "Turkmenistan manat",
    code: "TM",
  },
  {
    name: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    languages: ["English"],
    population: 31458,
    currency: "United States dollar",
    code: "TC",
  },
  {
    name: "Tuvalu",
    capital: "Funafuti",
    languages: ["English"],
    population: 10640,
    currency: "Australian dollar",
    code: "TV",
  },
  {
    name: "Uganda",
    capital: "Kampala",
    languages: ["English", "Swahili"],
    population: 33860700,
    currency: "Ugandan shilling",
    code: "UG",
  },
  {
    name: "Ukraine",
    capital: "Kiev",
    languages: ["Ukrainian"],
    population: 42692393,
    currency: "Ukrainian hryvnia",
    code: "UA",
  },
  {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    languages: ["Arabic"],
    population: 9856000,
    currency: "United Arab Emirates dirham",
    code: "AE",
  },
  {
    name: "United Kingdom",
    capital: "London",
    languages: ["English"],
    population: 65110000,
    currency: "British pound",
    code: "GB",
  },
  {
    name: "United States Minor Outlying Islands",
    capital: "",
    languages: ["English"],
    population: 300,
    currency: "United States Dollar",
    code: "UM",
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    languages: ["Spanish"],
    population: 3480222,
    currency: "Uruguayan peso",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    capital: "Tashkent",
    languages: ["Uzbek", "Russian"],
    population: 31576400,
    currency: "Uzbekistani so'm",
    code: "UZ",
  },
  {
    name: "Vanuatu",
    capital: "Port Vila",
    languages: ["Bislama", "English", "French"],
    population: 277500,
    currency: "Vanuatu vatu",
    code: "VU",
  },
  {
    name: "Viet Nam",
    capital: "Hanoi",
    languages: ["Vietnamese"],
    population: 92700000,
    currency: "Vietnamese đồng",
    code: "VN",
  },
  {
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    languages: ["French"],
    population: 11750,
    currency: "CFP franc",
    code: "WF",
  },
  {
    name: "Western Sahara",
    capital: "El Aaiún",
    languages: ["Spanish"],
    population: 510713,
    currency: "Moroccan dirham",
    code: "EH",
  },
  {
    name: "Yemen",
    capital: "Sana'a",
    languages: ["Arabic"],
    population: 27478000,
    currency: "Yemeni rial",
    code: "YE",
  },
  {
    name: "Zambia",
    capital: "Lusaka",
    languages: ["English"],
    population: 15933883,
    currency: "Zambian kwacha",
    code: "ZM",
  },
  {
    name: "Zimbabwe",
    capital: "Harare",
    languages: ["English", "Shona", "Northern Ndebele"],
    population: 14240168,
    currency: "Botswana pula",
    code: "ZW",
  },
];
